SLING-11181: Distinguish between permanent and transient package import failures and add metric on successful retries
apache/sling-org-apache-sling-distribution-journal pull request #105
Opened 2022-04-04 13:10 UTC by jose-correia

This PR addresses the change in [SLING-11181](https://issues.apache.org/jira/browse/SLING-11181).

We are change the `failed_package_imports` metric to also include a label with the type of failure, if it is `PERMANENT` and cannot be retried anymore, or if its `TRANSIENT` and will be retried.

Additionally we are adding a new metric `successfully_retried_package_imports` wich provides observability on the amount of packages that were retried successfully.

2022-04-04 13:14 UTC, jose-correia commented
🚨 whoever merges these changes, please change the commits JIRA key to SLING-11181, upon squash. I added the wrong key.

2022-04-04 13:16 UTC, kwin commented
> 🚨 whoever merges these changes, please change the commits JIRA key to SLING-11181, upon squash. I added the wrong key.

Just fix the commit messages and do a force push afterwards. You can also already squash.

2022-04-04 13:17 UTC, kwin commented on .java-version
> +1.8
Please remove this file

2022-04-04 13:19 UTC, jose-correia commented
Thanks @kwin! I assumed `--force` was forbidden

2022-04-05 12:11 UTC, tmaret requested changes

2022-04-05 12:11 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/shared/DistributionMetricsService.java
> +    private Meter successfullyRetriedPackageImports;
A "successfully retried package import" is essentially a measure of transient error.

I think we should rename that field (and getter) to `transientImportErrors` which is more concise.

I think we should also use a counter here instead of a meter.

2022-04-05 12:11 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/bookkeeper/BookKeeper.java
> +            distributionMetricsService.getFailedPackageImports("TRANSIENT").mark();
Labelling this error as transient is not accurate. It may be that the error is permanent.

I think we should remove the labelling of failed package imports and keep it as it is today. We'd introduce a new counter metric for permanent imports, likely `permanentImportErrors` alongside the metric `transientImportErrors` already introduced by this PR.

2022-04-06 13:41 UTC, jose-correia commented on src/main/java/org/apache/sling/distribution/journal/shared/DistributionMetricsService.java
> +    private Meter successfullyRetriedPackageImports;
I see where I was wrong here. I was classifying `transient` as `an error that may still be fixed in the future`, when in reality it's `something that failed temporarily but was now successful`

2022-04-06 13:41 UTC, jose-correia commented on src/main/java/org/apache/sling/distribution/journal/bookkeeper/BookKeeper.java
> +            distributionMetricsService.getFailedPackageImports("TRANSIENT").mark();
@tmaret agree with the comments

2022-04-06 14:01 UTC, jose-correia commented on src/main/java/org/apache/sling/distribution/journal/shared/DistributionMetricsService.java
> +    public Meter getFailedPackageImports(String type) {
will resolve, since the label is not being used anymore

2022-04-07 08:38 UTC, tmaret approved these changes

2022-04-07 08:38 UTC, merged