SLING-10077: Mode to raise events only locally
apache/sling-org-apache-sling-distribution-journal pull request #99
Opened 2022-02-21 11:07 UTC by balasoiuroxana

2022-02-22 11:31 UTC, tmaret requested changes

2022-02-22 11:31 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/PackageDistributedNotifier.java
> +        for (Map.Entry<String, LocalStore> localStoreEntry : this.localStores.entrySet()) {
Currently `localStoreEntry` starts empty. The loop will never set the `lastDistributedOffsets` field from stored values. This could be solved by loading the `lastDistributedOffsets` if needed and upon use in the `processOffsets` method.

This loop in the activate method would be removed. Computing `minOffset` in `processOffsets` would be done with somethings along the lines of

```
long minOffset = Math.min(offsets.get().findFirst().getAsLong(), lastDistributedOffsets.computeIfAbsent(pubAgentName, this::storedLastDistributedOffset));
```
and 
```
private long storedLastDistributedOffset(String pubAgentName) {
    return localStores.computeIfAbsent(pubAgentName, this::newLocalStore).load(STORE_TYPE_OFFSETS, Long.MAX_VALUE);
}
```

The `storeLastDistributedOffset` would no longer create `LocalStore` with `computeIfAbsent` and instead simply skip stores not present in the `localStores` field.

2022-02-22 11:31 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/PackageDistributedNotifier.java
> +    private Map<String, LocalStore> localStores;
`localStores` should be a thread safe `ConcurrentMap` instead of `HashMap` because it'll be accessed from multiple threads: the task that invoke `storeLastDistributedOffset` and the thread that invoke `processOffsets`.

2022-02-22 11:35 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/PackageDistributedNotifier.java
> +    private final Map<String, Long> lastDistributedOffsets = new HashMap<>();
`lastDistributedOffsets` should be a thread safe `ConcurrentMap` as it is accessed concurrently by different threads.

2022-02-22 11:37 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/PackageDistributedNotifier.java
> +    private  MessagingProvider messagingProvider;
Please set `messagingProvider`, `topics`, and `resolverFactory` as `final`

2022-02-22 13:52 UTC, tmaret requested changes

2022-02-22 13:52 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/DistributedEventNotifierManager.java
> +    private boolean isLeader;
`isLeader` is redundant with the `reg`. The `isLeader` method could be implemented with

```
return (reg != null)
```
and the `isLeader` field removed.

2022-02-22 13:52 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/DistributedEventNotifierManager.java
> +    private void registerService() {
I missed this during the first review, sorry. The `registerService` and `unregisterService` access to `reg` should be synchronised as it's invoked from multiple threads. The easiest way is probably to add the `synchronized` keyword to both methods.

2022-02-22 13:52 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/PackageDistributedNotifier.java
> +                } catch (Exception  e) {
Please add a logging statement at INFO level to capture that the offset xyz has been stored for the pubAgentName abc

2022-02-22 13:52 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/PackageDistributedNotifierStoreTask.java
> +                PROPERTY_SCHEDULER_PERIOD + ":Long=" + 60, // 1 minute
Although we can configure it, I think we should use a slower rate by default, maybe 10 minutes.

2022-02-22 13:52 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/PackageDistributedNotifier.java
> +            lastDistributedOffsets.put(pubAgentName, (Long)(queueItem.get(QueueItemFactory.RECORD_OFFSET)));
We should guard against potential case where the record offset is null. queueItem should default to `Long.MAX_VALUE`

2022-02-22 14:41 UTC, balasoiuroxana commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/DistributedEventNotifierManager.java
> +    private boolean isLeader;
I used `isLeader` only for testing and its purpose is a little different from (reg != null), because if we have the default config, reg is not null although the instance can be or not the leader .

2022-02-22 16:33 UTC, balasoiuroxana commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/DistributedEventNotifierManager.java
> +    private boolean isLeader;
I addressed this [here](https://github.com/apache/sling-org-apache-sling-distribution-journal/pull/99/commits/3af279d779cc63956836b1ca0e92118efdb8051b).

2022-02-23 08:26 UTC, tmaret requested changes

2022-02-23 08:26 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/PackageDistributedNotifierStoreTask.java
> +public class PackageDistributedNotifierStoreTask implements Runnable {
Bummer. The service exported by the `DistributedEventNotifierManager` is a `TopologyChangeHandler` and not a `PackageDistributedNotifier`. So the `notifier` reference is never resolved.

I think we should remove the `PackageDistributedNotifierStoreTask` and instead have the `DistributedEventNotifierManager` implement `Runnable` with something along the lines of

```
@Override
    public void run() {
/*
     * To avoid conflicting writes, only the leader instance
     * persists the last distributed offset in the repository.
     *
     * The task runs at a frequency of 1 minute to avoid
     * overloading the author repository with a steady stream
     * of fast commits (approximately 10 commit per second).
     */

        notifier.storeLastDistributedOffset();
    }
```

We'd move the component properties (`PROPERTY_SCHEDULER_CONCURRENT`, `PROPERTY_SCHEDULER_IMMEDIATE `, etc.) to the `DistributedEventNotifierManager` component as well. The `DistributedEventNotifierManager` component would also need to expose two services, a `TopologyEventListener` and `Runnable`. The component would be defined with something along the lines of

```
@Component(immediate = true, service = {TopologyEventListener.class, Runnable.class}, property = {
        PROPERTY_SCHEDULER_CONCURRENT + ":Boolean=false",
        PROPERTY_SCHEDULER_IMMEDIATE + ":Boolean=true",
        PROPERTY_SCHEDULER_PERIOD + ":Long=" + 60 * 10, // 10 minutes
        PROPERTY_SCHEDULER_RUN_ON + "=" +  VALUE_RUN_ON_LEADER
})
```

2022-02-23 08:26 UTC, tmaret commented on src/main/java/org/apache/sling/distribution/journal/impl/publisher/DistributedEventNotifierManager.java
> +            TopologyChangeHandler notifier = new PackageDistributedNotifier(eventAdmin, pubQueueCacheService, messagingProvider, topics, resolverFactory);
The `notifier` should move to a private field and be instantiated in the activate method. The `registerService` and `unregisterService` method would register respectively unregister the instance in the field.

2022-02-25 08:57 UTC, tmaret approved these changes

2022-02-25 09:02 UTC, merged